### PR TITLE
[CT-7773] bump @floating-ui/react to 0.24.8

### PR DESCRIPTION
**Pull request by rv2e**
Related ticket: https://datacamp.atlassian.net/browse/CT-7773

- bump @floating-ui/react to 0.24.8

### 🚨 Breaking Changes

No

### 🚀 Major Changes

No

### 🔧 Minor Changes

- Bunch of bug fixes: https://github.com/floating-ui/floating-ui/releases?q=%40floating-ui%2Freact&expanded=true

### ❓ Misc Changes

- Bump floating UI package

## Screenshot(s):

/

### CODE REVIEW

**Review by lensbart — APPROVED** [review]
LGTM

**Review by entropitor — APPROVED** [review]

**Comment by rv2e** [comment]
@ixTec It seems there is a building issue because of the type definition in the floating package. Given there are multiple ways to fix that I'll let you handle it if it's fine ;)

Just so you know it fixes a bug in our app (Workpace). We used "yarn resolutions" to fix the problem on our side temporarily (https://github.com/datacamp-engineering/collab-and-tooling/pull/4027).

**Comment by ixTec** [comment]
@rv2e Can you please take a look at https://github.com/datacamp/waffles/blob/master/docs/CONTRIBUTING.md?

We wouldn't consider a (minor) dependency update a `feat`, but a `chore` instead.

I'll likely take a look at the typing issue tomorrow

**Comment by rv2e** [comment]
@ixTec Sorry I wasn't aware of the conventions. I updated my commit message ;)

**Pull request merged**
